fix macos sdl build error (define -D_XOPEN_SOURCE)
Fixes macos sdlfrotz build.

Make log:

Build error:

In file included from sf_sig.c:77:

/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/\
usr/include/ucontext.h:43:2:

error: The deprecated ucontext routines require _XOPEN_SOURCE to be
defined #error The deprecated ucontext routines require _XOPEN_SOURCE to
be defined