Makefile: blorb-lib needs hash.h
If running "make blorb-lib" on a vanilla source directory, the
compilation fails with:

 make -C src/blorb
 make[1]: Entering directory '/home/thomas/src/frotz/src/blorb'
 cc -Wall -std=c99 -O3  -g -D_POSIX_C_SOURCE=200809L -I../common -fPIC
  -fpic -o blorblib.o -c blorblib.c
 In file included from blorblib.c:11:
 ../common/frotz.h:74:10: fatal error: hash.h: No such file or directory
    74 | #include "hash.h"
       |          ^~~~~~~~
 compilation terminated.

Looks like we also have to make sure that hash.h is in place before
compiling the blorb target, thus add the dependency to the Makefile.